@Library("jenlib") _

try {
	node {
		cleanWs()
	}

	inSingularity(app: "visionary-dls") {
		stage('Checkout') {
			runOnSlave(label: "frontend") {
				withWaf() {
					if (env.GERRIT_CHANGE_NUMBER) {
						sish "waf setup " +
						     "--project binutils-gdb@binutils-2_25-branch-nux " +
						     "--project gcc@nux-on-gcc-4_9_4-release " +
						     "--project newlib@master " +
						     "--clone-depth 1 " +
						     "--gerrit-changes=${GERRIT_CHANGE_NUMBER} " +
						     "--gerrit-url=ssh://hudson@$GERRIT_HOST:$GERRIT_PORT"
					} else {     // Jenkinsfile not called via Gerrit
						sish "waf setup " +
						     "--project binutils-gdb@binutils-2_25-branch-nux " +
						     "--project gcc@nux-on-gcc-4_9_4-release " +
						     "--project newlib@master " +
						     "--clone-depth 1"
					}
				}
				sish "bash gcc/ci/00_download_prerequisites.sh"
			}
		}

		stage("Build") {
			onSlurmResource(partition: "jenkins", "cpus-per-task": "8") {
				sish "bash binutils-gdb/ci/00_build_install.sh"
				sish "bash gcc/ci/01_build_install_freestanding.sh"
				sish "bash newlib/ci/00_build_install.sh"
			}
		}
	}

} catch (Exception e) {
	notifyFailure(mattermostChannel: "#dls-software")
	throw e as java.lang.Throwable
} finally {
	// Always clean the workspace
	node {
		cleanWs()
	}
}

// Some Jenkins steps fail a build without raising (e.g. archiveArtifacts)
if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}